trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: Default   # uses your self-hosted agent

variables:
  ARTIFACT_NAME: drop
  BUILD_DIR: $(Build.SourcesDirectory)
  ZIP_PATH: $(Build.ArtifactStagingDirectory)/app.zip

steps:
# 1. Checkout GitHub repo
- checkout: self

# 2. Install dependencies
- script: |
    cd $(BUILD_DIR)
    npm ci
  displayName: "Install dependencies"

# 3. Run tests
- script: |
    cd $(BUILD_DIR)
    npm test --if-present
  displayName: "Run tests"

# 4. Archive source code
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(BUILD_DIR)'
    archiveType: 'zip'
    archiveFile: '$(ZIP_PATH)'
    replaceExistingArchive: true
  displayName: "Archive project"

# 5. Publish artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: '$(ARTIFACT_NAME)'
    publishLocation: 'Container'
  displayName: "Publish artifact"
